/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-armv4"
#define DATE "built on: Tue Feb  7 13:43:33 2023 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','x','i',
    'l','i','n','x','-','l','i','n','u','x','-','g','n','u','e','a',
    'b','i','-','g','c','c',' ',' ','-','m','t','h','u','m','b',' ',
    '-','m','f','p','u','=','n','e','o','n',' ','-','m','f','l','o',
    'a','t','-','a','b','i','=','h','a','r','d',' ','-','m','c','p',
    'u','=','c','o','r','t','e','x','-','a','9',' ','-','f','s','t',
    'a','c','k','-','p','r','o','t','e','c','t','o','r','-','s','t',
    'r','o','n','g',' ',' ','-','O','2',' ','-','D','_','F','O','R',
    'T','I','F','Y','_','S','O','U','R','C','E','=','2',' ','-','W',
    'f','o','r','m','a','t',' ','-','W','f','o','r','m','a','t','-',
    's','e','c','u','r','i','t','y',' ','-','W','e','r','r','o','r',
    '=','f','o','r','m','a','t','-','s','e','c','u','r','i','t','y',
    ' ','-','-','s','y','s','r','o','o','t','=','r','e','c','i','p',
    'e','-','s','y','s','r','o','o','t',' ','-','O','2',' ','-','p',
    'i','p','e',' ','-','g',' ','-','f','e','l','i','m','i','n','a',
    't','e','-','u','n','u','s','e','d','-','d','e','b','u','g','-',
    't','y','p','e','s',' ','-','f','m','a','c','r','o','-','p','r',
    'e','f','i','x','-','m','a','p','=',' ',' ','-','f','d','e','b',
    'u','g','-','p','r','e','f','i','x','-','m','a','p','=',' ',' ',
    '-','f','m','a','c','r','o','-','p','r','e','f','i','x','-','m',
    'a','p','=',' ',' ','-','f','d','e','b','u','g','-','p','r','e',
    'f','i','x','-','m','a','p','=',' ',' ','-','f','d','e','b','u',
    'g','-','p','r','e','f','i','x','-','m','a','p','=',' ',' ','-',
    'f','m','a','c','r','o','-','p','r','e','f','i','x','-','m','a',
    'p','=',' ',' ','-','f','d','e','b','u','g','-','p','r','e','f',
    'i','x','-','m','a','p','=',' ',' ','-','D','O','P','E','N','S',
    'S','L','_','U','S','E','_','N','O','D','E','L','E','T','E',' ',
    '-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D',
    'O','P','E','N','S','S','L','_','B','U','I','L','D','I','N','G',
    '_','O','P','E','N','S','S','L',' ','-','D','N','D','E','B','U',
    'G','\0'
};
