name: Pull Request Benchmark Workflow
on:
  pull_request:
    types: [opened, synchronize , reopened , labeled]
    paths:
      - ".github/workflows/*"
      - "Scripts/*"
      - "**/CMakeLists.txt"
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**.hpp"

jobs:

#========================================
# Checks
#========================================

  check_formatting:
    runs-on: ubuntu-22.04
    name: Check Formatting
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -u Scripts/CheckFormattingAll_c_h_cpp_hpp.py

#========================================
# Target Ubuntu - Host Ubuntu
#========================================

  target_ubuntu_host_ubuntu:
    needs: check_formatting
    permissions:
      pull-requests: write
    uses: ./.github/workflows/build-test-run-reusable-workflow.yaml
    with:
      runner: 'ubuntu-22.04'
      host-platform: 'ubuntu'
      target-platform: 'host'

#========================================
# Target Windows - Host Windows
#========================================

  target_windows_host_windows:
    needs: check_formatting
    permissions:
      pull-requests: write
    uses: ./.github/workflows/build-test-run-reusable-workflow.yaml
    with:
      runner: 'windows-2022'
      host-platform: 'windows'
      target-platform: 'host'

#========================================
# Target Zynq - Host Ubuntu
#========================================

  # build_target_zynq_host_ubuntu:
  #   needs: check_formatting
  #   permissions:
  #     pull-requests: write
  #   uses: ./.github/workflows/build-test-run-reusable-workflow.yaml
  #   with:
  #     runner: 'ubuntu-22.04'
  #     host-platform: 'ubuntu'
  #     target-platform: 'zynq'


#========================================
# Target Zynq - Host Windows
#========================================

  build_target_zynq_host_windows:
    needs: check_formatting
    permissions:
      pull-requests: write
    uses: ./.github/workflows/build-test-run-reusable-workflow.yaml
    with:
      runner: 'windows-2022'
      host-platform: 'windows'
      target-platform: 'zynq'
